### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by ghost** [gaddes/prj-rev-bwfs-dasmoto#8]
Satisfactory 👍 

You've successfully reproduced the website according to the design mock. You've demonstrated a solid understanding of using HTML to markup your page's content and structure and of using CSS to apply fundamental styles.

Try to make more strategic use of class names and IDs so that your code is as self-documenting as possible.

**Comment by gaddes** [comment]
Thanks again for all your comments Steve, really useful!
